version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-net
    volumes:
      - ./:/home/app
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - app-net
  training-helper:
    build:
      args:
        user: 1000
        uid: 1000
      context: .
    working_dir: /home/app
    volumes:
      - ./:/home/app
    env_file:
      - .env
    ports:
      - 3500:3500
    depends_on:
      - mongodb
    networks:
      - app-net
networks:
  app-net:
