swagger: "2.0"
info:
  title: My API
  version: 1.0.0
tags:
  - name: Auth
    description: Authentication and user management
  - name: Trainings
    description: Trainings CRUD
components:
  schemas:
    User:
      $ref: './schemes/auth/User.yaml'
    Training:
      $ref: './schemes/training/Training.yaml'
paths:
  /auth/register:
    $ref: './paths/auth/Register.yaml'
  /auth/login:
    $ref: './paths/auth/Login.yaml'
  /auth/refresh:
    $ref: './paths/auth/Refresh.yaml'
  /auth/logout:
    $ref: './paths/auth/Logout.yaml'
  /trainings:
    $ref: './paths/trainings/Trainings.yaml'
  /trainings/{trainingId}:
    $ref: './paths/trainings/Trainings.trainingId.yaml'
  /trainings/user:
    $ref: './paths/trainings/Trainings.user.yaml'
